site_name: AI Learning Group
site_dir: site
docs_dir: docs
use_directory_urls: true 

theme:
  name: material

  palette:
    scheme: default #slate #> dark mode
    primary: indigo
    accent: blue

  features:
      # Makes the main navigation items appear as a top bar for a cleaner look
      - navigation.tabs
      # Keeps the table of contents visible while scrolling
      - toc.follow
      # Enables the "Back to top" button
      - content.action.top
      # Adds a copy button to code blocks (great motivation for users to try code!)
      - content.code.copy
      # Shows the hierarchy of the current page in the header
      - navigation.path
      # Expands all navigation sections by default
      #- navigation.expand

  font:
    text: Roboto
    code: Roboto Mono


markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.pathconverter
  - attr_list
extra_css:
  - css/extra.css
plugins:
  - search
  - mkdocs-pdf
  - mkdocs-jupyter:
      execute: true

nav:
  - Home: README.md

  - AI Tools Hands-on:
    - Beginners - Local AI : ai-tools-hands-on/Beginners-guide-to-Local_AI.md
    - Private Local & Free GuFF models: ai-tools-hands-on/AccessWorldOfFreeLLMs-guff/How-to-freely-access-use-LLMs-locally-securely-with-no-limits.md
    - Top Local LLMs: ai-tools-hands-on/CuratedLocalLLMs/Top-Local-LLMs.md
    - 2025 - Future of Local LLMs: ai-tools-hands-on/Wide-future-of-local-llms/future-of-opensource-local-llms.md
    - AI Local Deployements:
      - Gemma4 with TurboQuant on Ollama : ai-tools-hands-on/local-ai-model-deployements/gemma4-with-ollama-turboquant.md
      - Ollama + TQuant + Claude : ai-tools-hands-on/Turboquant/docs/ollama-cmd-TBQ.md
    - AI Tools:
      - OpenClaw Paradigm & Risk: ai-tools-hands-on/AI-tool-guides/Open-claw-safety.md
    
  - AI Workflows:
    - n8n:
      - Overview & features: ai-workflows/n8n/docs/n8n-overview.md
      - Private-Secure Docker-Desktop n8n + local LLM: ai-workflows/n8n/Local_N8N_setup_with_Local_AI/Step-by-step-guide-to-setup-n8n-locally-with-llm.md
      - Private-Secure Docker-Compose n8n + local LLM: ai-workflows/n8n/Local_N8N_setup_with_Local_AI/n8n-setup-with-docker-compose.md

  - AI - Prompts:
    - Zero Shot Prompts: ai-tools-hands-on/Prompts/Zero-shot-prompting.md
    - Save Prompt Cost: ai-tools-hands-on/Prompts/Effective-prompts-save-premium-requests-n-cost.md


  - Linux:
    - Linux Home: Linux/Linux-home.md
    - Ubuntu Guide: Linux/Ubuntu/ubuntu-Install-modes-full-guide.md
    - Ubuntu AI Pro: Linux/Ubuntu/Ubuntu-26.0-AI-Redefined.md
    - Zorin Guide: Linux/Zorin/Zorin-Install-Full-Guide.md
    - Low RAM > Swap Memory : Linux/Linux-swapiness.md
    - World of free tools: Linux/Ubuntu/Linux-Tools.md
    - One Step Dev Env : Linux/Linux-Dev-Env-Setup/One-step-dev-setup-guide.md

