[project]
name = "turbo-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.13.0",
    "lmstudio>=1.5.0",
    "torch>=2.11.0",
    "transformers>=5.5.0",
    "ttkbootstrap>=1.20.2",
    "turboquant>=0.2.0",
]
