# TYPE|PACKAGE_NAME
# format rules:
# APT|package
# SNAP|package|classic(optional)
# FLATPAK|package

# Creative & Office (Switching to APT for guaranteed App Drawer icons)
APT|gimp
APT|libreoffice
APT|inkscape
APT|kdenlive
APT|audacity
APT|vlc

# Graphics (Only keep Flatpak if you really want the latest version)
FLATPAK|org.kde.krita
FLATPAK|org.gnome.Snapshot
FLATPAK|no.mifi.losslesscut

# Database & System (APT/Snap)
APT|postgresql
APT|postgresql-contrib
APT|virt-manager
SNAP|dbeaver-ce|classic
